[functions]
directory = "netlify/functions"

# Friendly URL → function for starting OAuth
[[redirects]]
from = "/auth/start"
to = "/.netlify/functions/auth-start"
status = 200

# Proxy all /api/* to our function
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/mal-proxy"
status = 200
